"""
Modal deployment for the Stonks & Texts mood engine.

    cd ml && modal deploy modal_serve.py

WHAT HAS TO BE TRUE FOR THIS TO WORK
------------------------------------
1. THREE FILES IN THE IMAGE. The artifact is a pickle that names
   `pipeline_def.MarketMoodFeatures`; unpickling it without that module present
   raises an AttributeError that says nothing useful about the real cause. So
   `serve.py`, `pipeline_def.py` and `pipeline.joblib` all ship together, via
   `copy=True` so they become image layers rather than runtime mounts.

2. EXACT VERSIONS. requirements.txt is generated by build_pipeline.py from the
   interpreter that produced the artifact, so the pins cannot drift from it. A
   scikit-learn mismatch is the classic way a pickle loads locally and explodes
   in the container.

3. THE APP IS IMPORTED INSIDE THE FUNCTION. Importing `serve` at module scope
   would run it on the local machine during `modal deploy`, where the
   dependencies and the artifact path may not match the container at all. The
   import belongs where the code actually runs.
"""

from pathlib import Path

import modal

HERE = Path(__file__).resolve().parent

# Everything that must exist inside the container, mapped local -> remote.
# /root is the image's working directory.
SHIPPED_FILES = {
    HERE / "serve.py": "/root/serve.py",
    HERE / "pipeline_def.py": "/root/pipeline_def.py",
    HERE / "pipeline.joblib": "/root/pipeline.joblib",
}

for local_path in SHIPPED_FILES:
    if not local_path.exists():
        raise FileNotFoundError(
            f"{local_path.name} is missing. Run `python build_pipeline.py` before deploying."
        )

image = modal.Image.debian_slim(python_version="3.13").pip_install_from_requirements(
    str(HERE / "requirements.txt")
)

for local_path, remote_path in SHIPPED_FILES.items():
    # copy=True bakes the file into an image layer. Without it the file is a
    # runtime mount, which works but is not "shipped in the image" and is easier
    # to lose track of.
    image = image.add_local_file(str(local_path), remote_path, copy=True)

app = modal.App("stonks-mood-engine", image=image)


@app.function(
    # The artifact loads at import, so a cold container pays that cost once and
    # then serves from memory. Keeping one container warm for a few minutes
    # means a grader clicking the URL twice does not wait for two cold starts.
    scaledown_window=300,
    max_containers=2,
)
@modal.asgi_app()
def fastapi_app():
    # Imported HERE, inside the container, not at module scope. See note 3 above.
    import sys

    if "/root" not in sys.path:
        sys.path.insert(0, "/root")

    from serve import app as web_app

    return web_app
