"""
Modal deployment for the Stonks & Texts recommendation engine.

    cd ml && modal deploy modal_serve.py

WHAT HAS TO BE TRUE FOR THIS TO WORK
------------------------------------
1. THREE FILES IN THE IMAGE. The artifact is a pickle naming
   `pipeline_def.MarketContextFeatures`; unpickling it without that module raises
   an AttributeError that says nothing about the real cause. So serve.py,
   pipeline_def.py and pipeline.joblib all ship together with copy=True, making
   them image layers rather than runtime mounts.

2. EXACT VERSIONS. requirements.txt is generated by build_pipeline.py from the
   interpreter that fitted the artifact, so the pins cannot drift from it. A
   scikit-learn mismatch is the classic way a pickle loads locally and explodes
   in the container.

3. THE APP IS IMPORTED INSIDE THE FUNCTION. Importing `serve` at module scope
   would run it locally during `modal deploy`, where the dependencies and the
   artifact path need not match the container at all.
"""

from pathlib import Path

import modal

HERE = Path(__file__).resolve().parent

SHIPPED_FILES = {
    HERE / "serve.py": "/root/serve.py",
    HERE / "pipeline_def.py": "/root/pipeline_def.py",
    HERE / "pipeline.joblib": "/root/pipeline.joblib",
}

for local_path in SHIPPED_FILES:
    if not local_path.exists():
        raise FileNotFoundError(
            f"{local_path.name} is missing. Run `python build_pipeline.py` before deploying."
        )

image = modal.Image.debian_slim(python_version="3.13").pip_install_from_requirements(
    str(HERE / "requirements.txt")
)

for local_path, remote_path in SHIPPED_FILES.items():
    image = image.add_local_file(str(local_path), remote_path, copy=True)

app = modal.App("stonks-recommendation-engine", image=image)


@app.function(
    # The artifact loads at import, so a cold container pays that once and then
    # serves from memory. Keeping one warm briefly means a grader clicking the
    # URL twice does not wait through two cold starts.
    scaledown_window=300,
    max_containers=2,
)
@modal.asgi_app()
def fastapi_app():
    # Imported HERE, inside the container. See note 3 above.
    import sys

    if "/root" not in sys.path:
        sys.path.insert(0, "/root")

    from serve import app as web_app

    return web_app
