-- ============================================================================
--  STONKS & TEXTS -- SCHEMA
-- ============================================================================
--  Run once in the Supabase SQL editor (Dashboard -> SQL Editor -> New query).
--  Safe to re-run: it drops and recreates everything. The seed script
--  (npm run seed) repopulates assets, price_history and messages afterwards.
--
--  There is no auth. This is a single-demo-user paper trading app, so the sim
--  state lives in one row and RLS policies are deliberately open to `anon`.
--  That is a conscious choice for a class project, not an oversight -- see the
--  policy block at the bottom.
-- ============================================================================

drop table if exists trades            cascade;
drop table if exists messages          cascade;
drop table if exists price_history     cascade;
drop table if exists sim_state         cascade;
drop table if exists assets            cascade;

-- ---------------------------------------------------------------------------
-- assets: the twelve tickers that text you
-- ---------------------------------------------------------------------------
create table assets (
  id        bigserial primary key,
  ticker    text not null unique,
  name      text not null,
  type      text not null check (type in ('stock', 'crypto')),
  category  text not null,
  -- Hex colour for the avatar circle, so the asset's identity is consistent
  -- across the sidebar, the chat header, the P&L list and every chart series.
  color     text not null
);

-- ---------------------------------------------------------------------------
-- price_history: adjusted daily OHLCV, ~2 years per asset
-- ---------------------------------------------------------------------------
create table price_history (
  asset_id  bigint not null references assets(id) on delete cascade,
  date      date   not null,
  open      double precision not null,
  high      double precision not null,
  low       double precision not null,
  close     double precision not null,
  volume    bigint not null,
  primary key (asset_id, date)
);

-- The portfolio valuation walks every asset day by day, so `date` leads.
create index price_history_date_idx on price_history (date);

-- ---------------------------------------------------------------------------
-- messages: pre-generated by the rules engine in src/lib/messages/rules.ts
-- ---------------------------------------------------------------------------
--  Storing rather than computing on the fly is deliberate:
--    * the rules engine's output is inspectable in plain SQL, which is exactly
--      what makes the model defensible rather than a black box;
--    * sidebar previews and unread counts become one indexed query instead of
--      recomputing 12 assets x 500 days on every render;
--    * determinism is provable -- re-run the seed, diff the table, get nothing.
--  The engine remains the single source of truth; this table is its output.
-- ---------------------------------------------------------------------------
create table messages (
  id            bigserial primary key,
  asset_id      bigint not null references assets(id) on delete cascade,
  date          date   not null,
  -- Which rule fired. Mirrors RuleId in the engine.
  rule          text   not null check (rule in (
                  'new_52w_high', 'new_52w_low', 'big_gain', 'big_drop',
                  'losing_streak', 'winning_streak', 'volume_spike', 'mundane')),
  tone          text   not null,
  body          text   not null,
  -- 1-5. >= 4 marks a big mover and lights the unread dot in the sidebar.
  priority      int    not null,
  -- The numbers that triggered the message, snapshotted so the Data tab can
  -- chart "what the model saw" without recomputing indicators.
  pct_change    double precision not null,
  volume_ratio  double precision not null,
  close         double precision not null,
  -- At most one message per asset per day: the engine picks a single winning
  -- rule, so this constraint is what makes `npm run seed` safely re-runnable.
  unique (asset_id, date)
);

create index messages_date_idx           on messages (date);
create index messages_asset_date_idx     on messages (asset_id, date desc);

-- ---------------------------------------------------------------------------
-- sim_state: where the single demo user currently is in history
-- ---------------------------------------------------------------------------
--  The app plays forward through the last 12 months of the dataset. This one
--  row is the clock. `sim_date` (not `current_date`, which is a SQL builtin)
--  is the day whose closes trades execute at.
-- ---------------------------------------------------------------------------
create table sim_state (
  id            int primary key default 1 check (id = 1),
  sim_date      date not null,
  -- Uninvested fake dollars.
  cash          double precision not null,
  starting_cash double precision not null,
  updated_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- trades: the paper-trade ledger
-- ---------------------------------------------------------------------------
--  Every tap of sell / hold / buy writes one row, including 'hold' with a zero
--  quantity. Logging holds costs nothing and turns "how often did I do nothing,
--  and was that right?" into an answerable question on the Data tab.
--
--  `trade_date` is the SIM date the trade executes at, which is what the
--  backtest uses. `created_at` is real wall-clock time and is only there for
--  ordering ties and debugging. Do not confuse the two.
-- ---------------------------------------------------------------------------
create table trades (
  id          bigserial primary key,
  asset_id    bigint not null references assets(id) on delete cascade,
  -- Which text prompted this reply. Null if traded from the portfolio view.
  message_id  bigint references messages(id) on delete set null,
  action      text   not null check (action in ('buy', 'sell', 'hold')),
  -- Execution price = that sim day's close.
  price       double precision not null,
  -- Fractional shares are allowed; a fixed $500 bet rarely divides evenly.
  quantity    double precision not null check (quantity >= 0),
  -- price * quantity, stored so the ledger reads correctly without a join.
  notional    double precision not null,
  trade_date  date not null,
  created_at  timestamptz not null default now()
);

create index trades_asset_idx      on trades (asset_id);
create index trades_trade_date_idx on trades (trade_date);

-- ---------------------------------------------------------------------------
-- Portfolio value over time
-- ---------------------------------------------------------------------------
--  Intentionally NOT a table. The equity curve is derived from `trades` joined
--  against `price_history`, and it is recomputed in src/lib/portfolio.ts.
--
--  Why compute instead of store: in this app you can trade at any point in the
--  sim window, and any new trade invalidates every snapshot after its date. A
--  snapshot table would need cache invalidation on every single tap, and a
--  stale row would silently corrupt the headline "did you beat buy-and-hold?"
--  number. Deriving it from the ledger means the chart cannot disagree with
--  the trades that produced it. It is 12 assets x ~365 days -- microseconds.
--
--  This view exposes the same daily position data to SQL for inspection.
-- ---------------------------------------------------------------------------
--  `security_invoker = true` matters: without it a Postgres view runs with its
--  OWNER's permissions and quietly bypasses the RLS policies below. This view
--  only exposes data anon can already read, so it isn't a leak either way -- but
--  a view that ignores RLS is the wrong default to leave in a schema.
create or replace view daily_positions with (security_invoker = true) as
select
  p.date,
  a.ticker,
  p.close,
  -- Running share count held on each date: every buy adds, every sell removes.
  coalesce(sum(
    case t.action when 'buy' then t.quantity when 'sell' then -t.quantity else 0 end
  ) filter (where t.trade_date <= p.date), 0) as shares
from price_history p
join assets a on a.id = p.asset_id
left join trades t on t.asset_id = p.asset_id
group by p.date, a.ticker, p.close
order by p.date, a.ticker;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
--  The app ships no login, so the browser talks to Postgres with the public
--  key -- either a legacy `anon` JWT or a new-format `sb_publishable_...` key.
--  Both resolve to the `anon` Postgres role, so these policies cover both.
--  RLS is ON everywhere; the policies below grant exactly what the demo needs
--  and nothing more:
--    * read-only on the seeded reference data (assets, prices, messages)
--    * insert on trades and update on sim_state, because playing the sim is
--      the entire point of the app
--  Nobody can delete or rewrite the seeded market data through the public key;
--  `npm run seed` uses the secret/service_role key, which bypasses RLS.
--  If this were handling real users it would need auth and per-user rows.
-- ---------------------------------------------------------------------------
alter table assets        enable row level security;
alter table price_history enable row level security;
alter table messages      enable row level security;
alter table trades        enable row level security;
alter table sim_state     enable row level security;

create policy "read assets"        on assets        for select to anon, authenticated using (true);
create policy "read price_history" on price_history for select to anon, authenticated using (true);
create policy "read messages"      on messages      for select to anon, authenticated using (true);

create policy "read trades"        on trades        for select to anon, authenticated using (true);
create policy "log trades"         on trades        for insert to anon, authenticated with check (true);
-- Resetting the demo clears the ledger, so anon needs delete on trades only.
create policy "reset trades"       on trades        for delete to anon, authenticated using (true);

create policy "read sim_state"     on sim_state     for select to anon, authenticated using (true);
create policy "advance sim"        on sim_state     for update to anon, authenticated using (true) with check (true);

-- Views don't inherit table grants; without this the app gets a 401 on the view.
grant select on daily_positions to anon, authenticated;
